spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'M*EAs4d&5ojlk2B#*'
    url: jdbc:mysql://localhost:3306/sd_data?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&characterEncoding=utf8&characterSetResults=utf8
