spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://132.232.125.247:23306/alk_cpsp_190628?useUnicode=true&serverTimezone=Asia/Shanghai&autoReconnect=true
  freemarker:
    suffix: .html
